services:
  api:
    image: flask-user-health-api:prod
    container_name: flask_user_health_api_prod
    ports:
      - "5060:5000"
    environment:
      - APP_VERSION=prod
    restart: unless-stopped
